### PR TITLE
Make Kafka brokers optional

### PR DESCRIPTION
**Pull request by philipp94831**

### CODE REVIEW

**Comment by disrupted** [comment]
please rebase and a add a description where this change originates from

**Comment by raminqaf** [comment]
@philipp94831 What is the status of this PR? 🙂

**Comment by philipp94831** [comment]
Not needed urgently. But there have been changes in streams-bootstrap which are reflected here

**Comment by raminqaf** [comment]
@philipp94831 Can it be closed?

**Comment by philipp94831** [comment]
No. It is still relevant but no priority

**Comment by disrupted** [comment]
closing as inactive, seems to be abandoned

**Pull request closed without merging**
